name: telissy
description: A high-level, resource-oriented Telegram client library for Dart.
version: 1.1.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.11.5

# Add regular dependencies here.
dependencies:
  tg: ^0.0.19
  t: ^225.0.0
  meta: ^1.18.2

dev_dependencies:
  build_runner: ^2.15.0
  coverage: ^1.15.0
  lints: ^6.0.0
  mockito: ^5.6.5
  test: ^1.25.6
